In [1]:
import pandas as pd

df = pd.read_csv("ventas_python_bigdata.csv")
print(df)

   ID     Nombre         Ciudad  Edad  Ventas   Categoria
0   1        Ana         Bogotá    23    1200  Tecnología
1   2       Luis       Medellín    31    1850       Hogar
2   3      María           Cali    27     980  Tecnología
3   4     Carlos   Barranquilla    35    2100    Deportes
4   5      Laura  Villavicencio    29    1750        Moda
5   6       Juan         Bogotá    41    2450  Tecnología
6   7      Sofía           Cali    22     890        Moda
7   8     Miguel       Medellín    38    1990       Hogar
8   9  Valentina         Bogotá    26    1540  Tecnología
9  10     Andrés  Villavicencio    33    1675    Deportes

In [2]:
# Ver los primeros datos 
# HEAD() -> 5 filas 
df.head()

   ID  Nombre         Ciudad  Edad  Ventas   Categoria
0   1     Ana         Bogotá    23    1200  Tecnología
1   2    Luis       Medellín    31    1850       Hogar
2   3   María           Cali    27     980  Tecnología
3   4  Carlos   Barranquilla    35    2100    Deportes
4   5   Laura  Villavicencio    29    1750        Moda

In [3]:
df.head(3)

   ID Nombre    Ciudad  Edad  Ventas   Categoria
0   1    Ana    Bogotá    23    1200  Tecnología
1   2   Luis  Medellín    31    1850       Hogar
2   3  María      Cali    27     980  Tecnología

In [8]:
# TAIL()
df.tail()

   ID     Nombre         Ciudad  Edad  Ventas   Categoria
5   6       Juan         Bogotá    41    2450  Tecnología
6   7      Sofía           Cali    22     890        Moda
7   8     Miguel       Medellín    38    1990       Hogar
8   9  Valentina         Bogotá    26    1540  Tecnología
9  10     Andrés  Villavicencio    33    1675    Deportes

In [4]:
# SHAPE 
df.shape

(10, 6)

In [5]:
# COLUMNS 
df.columns

Index(['ID', 'Nombre', 'Ciudad', 'Edad', 'Ventas', 'Categoria'], dtype='str')

In [6]:
# .info()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         10 non-null     int64
 1   Nombre     10 non-null     str
 2   Ciudad     10 non-null     str
 3   Edad       10 non-null     int64
 4   Ventas     10 non-null     int64
 5   Categoria  10 non-null     str
dtypes: int64(3), str(3)
memory usage: 612.0 bytes

In [7]:
# Decribe 
df.describe()

             ID       Edad       Ventas
count  10.00000  10.000000    10.000000
mean    5.50000  30.500000  1642.500000
std     3.02765   6.293736   499.918049
min     1.00000  22.000000   890.000000
25%     3.25000  26.250000  1285.000000
50%     5.50000  30.000000  1712.500000
75%     7.75000  34.500000  1955.000000
max    10.00000  41.000000  2450.000000

In [8]:
df["Nombre"]

0          Ana
1         Luis
2        María
3       Carlos
4        Laura
5         Juan
6        Sofía
7       Miguel
8    Valentina
9       Andrés
Name: Nombre, dtype: str

In [9]:
df[["Nombre","Ventas"]]

      Nombre  Ventas
0        Ana    1200
1       Luis    1850
2      María     980
3     Carlos    2100
4      Laura    1750
5       Juan    2450
6      Sofía     890
7     Miguel    1990
8  Valentina    1540
9     Andrés    1675

In [10]:
#Filtros
df[df["Ciudad"]== "Bogotá"]

   ID     Nombre  Ciudad  Edad  Ventas   Categoria
0   1        Ana  Bogotá    23    1200  Tecnología
5   6       Juan  Bogotá    41    2450  Tecnología
8   9  Valentina  Bogotá    26    1540  Tecnología

In [11]:
df[df["Ventas"]>1800]

   ID  Nombre        Ciudad  Edad  Ventas   Categoria
1   2    Luis      Medellín    31    1850       Hogar
3   4  Carlos  Barranquilla    35    2100    Deportes
5   6    Juan        Bogotá    41    2450  Tecnología
7   8  Miguel      Medellín    38    1990       Hogar

In [12]:
df.sort_values("Ventas")

   ID     Nombre         Ciudad  Edad  Ventas   Categoria
6   7      Sofía           Cali    22     890        Moda
2   3      María           Cali    27     980  Tecnología
0   1        Ana         Bogotá    23    1200  Tecnología
8   9  Valentina         Bogotá    26    1540  Tecnología
9  10     Andrés  Villavicencio    33    1675    Deportes
4   5      Laura  Villavicencio    29    1750        Moda
1   2       Luis       Medellín    31    1850       Hogar
7   8     Miguel       Medellín    38    1990       Hogar
3   4     Carlos   Barranquilla    35    2100    Deportes
5   6       Juan         Bogotá    41    2450  Tecnología

In [13]:
df.sort_values("Ventas", ascending=False)

   ID     Nombre         Ciudad  Edad  Ventas   Categoria
5   6       Juan         Bogotá    41    2450  Tecnología
3   4     Carlos   Barranquilla    35    2100    Deportes
7   8     Miguel       Medellín    38    1990       Hogar
1   2       Luis       Medellín    31    1850       Hogar
4   5      Laura  Villavicencio    29    1750        Moda
9  10     Andrés  Villavicencio    33    1675    Deportes
8   9  Valentina         Bogotá    26    1540  Tecnología
0   1        Ana         Bogotá    23    1200  Tecnología
2   3      María           Cali    27     980  Tecnología
6   7      Sofía           Cali    22     890        Moda

# Comandos Importantes 
- head()
- info()
- describe()

In [14]:
df.isnull().sum()

ID           0
Nombre       0
Ciudad       0
Edad         0
Ventas       0
Categoria    0
dtype: int64